// SPDX-License-Identifier: BlueOak-1.0.0
// SPDX-FileCopyrightText: 2024, 2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

= Linux OS setup in separate Steps

(Mostly a sysadmin things)

== Initialize the remote host

Run the top-most script with a remote target pointed in the first argument:

```
./steps-00-init [user@]hostname
```

Eg:

```sh
$ ./steps-00-init root@omn.ssh
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/sskras/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@omn.ssh's password:
Permission denied, please try again.
root@omn.ssh's password:
Executing /root/.bashrc
Executing /root/.bash_functions

Number of key(s) added: 1

Now try logging into the machine, with:   "ssh -o 'StrictHostKeyChecking=accept-new' 'root@omn.ssh'"
and check to make sure that only the key(s) you wanted were added.

Testing key-based SSH-auth:

Thu Mar  7 12:34:44 PM EET 2024  uid=0(root) gid=0(root) groups=0(root) logged in succesfully on omn
Thu Mar  7 12:34:44 PM EET 2024  Host summary:  12:34:44 up 8 days, 12:31,  5 users,  load average: 0.00, 0.00, 0.00
```

If it's an indirect SSH connection (eg. overlaying another SSH session like a reverse tunnel),
you may need to have your target described in `~/.ssh/config` in advance.

Eg:
```
Host omn.ssh
    IdentityFile ~/.ssh/id_rsa-saukrs
    Port 2222
    ProxyJump vps1128235
```

== Bootstrap the OS setup

Eg. ensure the OS configuration gets tracked via **etckeeper** by the `root`:
```sh
curl -s https://raw.githubusercontent.com/saukrs/linux-steps/main/steps-01-bootstrap | sh
```

Or ensure your prerequisite tools (eg. Git, Rsync, GNU Make) are installed by a _sudoer_:
```sh
curl -s https://raw.githubusercontent.com/saukrs/linux-steps/main/steps-01-bootstrap | sudo sh -s git rsync make
```
+++ <sup> +++
(works even with a password prompt, although its' message disappears)
+++ </sup> +++


\... the same via shortened URLs:

- &nbsp;
  +++ <sub> +++
  Via Twitter
  +++ </sub> +++
```sh
curl -L t.co/UIgzvkqDI4 | sh
curl -L t.co/UIgzvkqDI4 | sudo sh -s git make

```

- &nbsp;
  +++ <sub> +++
  Via inbox.LV
  +++ <br /> +++
  &nbsp;
  (unreliable, may fail when an ad gets inserted)
  +++ </sub> +++
```sh
curl -L inx.lv/JAx5K | sh
curl -L inx.lv/JAx5K | sudo sh -s git make

```
