#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2024 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Script to initialize a remote host.
#
# Eg. import the initial SSH key so the host can authenticate
# us and be managed via SSH in a non-interactive way further.
# ------------------------------------------------------------------------------------

# 00. Fail early:

set -e

# 04. Exit handler:

trap '
    Exit_code=$?

    echo
    echo "The script failed: ${Exit_code}"

' EXIT
# Via: https://unix.stackexchange.com/questions/520035/exit-trap-with-posix/520041#520041

# 10. Import the current/configured SSH key:

ssh-copy-id -o StrictHostKeyChecking=accept-new $1

# 20. Test the SSH key:

echo "Testing key-based SSH-auth:"
echo
ssh $1 'echo "$(date)  $(id) logged in succesfully on $(hostname)"' 2>/dev/null
ssh $1 'echo "$(date)  Host summary: $(uptime)"' 2>/dev/null

# 30. The initial bootstraping:

echo
ssh $1 "$(cat steps-01-bootstrap)"

# 40. The essential tools and system-wide configuration:

echo
ssh $1 "$(cat steps-02-system)"

# 99. Finished:

echo "The script succeeded."
