#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2024, 2025 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Set up operating environment for further steps (install the essential deps, etc.)
# Via: https://github.com/sskras/.files/blob/3d54677b3461d03a98d0d2cd51ace890d6fcc667/.local/bin/boot-home#L8-L17

software () {
    # TODO: package manager detection

    # On Debian:
    apt -y "$@" \
    || \
    # On CentOS Stream (RHEL 9.x):
    dnf -y "$@" \
    || \
    # On OpenWRT:
    opkg "$@" \

}

# 0, Fail early, be verbose about cmds in execution:
set -e
set -x

# 1, Check if any arguments are passed to the script:
if [ $# -gt 0 ]; then

    # 2, Install packages by the passed names:
    software install "$@"
    exit 0
fi

# 1, Install crucial software:
software install git

# TODO: make sure getaddrinfo() with AI_CANONNAME returns a name with domain
# Eg. by making /etc/resolv.conf to include `search lan` or other DN.
#
# Otherwise git is angry:
#    fatal: unable to auto-detect email address (got 'root@OpenMPTCProuter.(none)')

# 2, Mark start of Git-versioning of /etc:
cd /etc
git init
git commit --allow-empty -m "Directory tracking started."
cd

# 3, Start logging /etc changes:
software install etckeeper
