#! /usr/bin/env sh

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2024 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Set up operating environment for further steps (install the essential deps, etc.)
# Via: https://github.com/sskras/.files/blob/3d54677b3461d03a98d0d2cd51ace890d6fcc667/.local/bin/boot-home#L8-L17

software () {
    # On Debian:
    apt -y "$@"
}

# 0, Fail early, be verbose about cmds in execution:
set -e
set -x

# 1, Install crucial software:
software install make git

# 2, Mark start of Git-versioning of /etc:
cd /etc
git init
git commit --allow-empty -m "Directory tracking started."
cd

# 3, Start logging /etc changes:
apt install -y etckeeper
